services:
  dev:
    image: mcr.microsoft.com/devcontainers/python:3.12
    command: sleep infinity
    ports:
      - "8000:8000"
    volumes:
      - ../:/workspaces/product-pagination-performance
    depends_on:
      - productsdb
    environment:
      DB_HOST: productsdb
      DB_PORT: "5432"
      DB_NAME: productsdb
      DB_USER: user
      DB_PASSWORD: password
      PORT: "8000"
  productsdb:
    image: postgres:17.9
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
