services:
  dev:
    image: mcr.microsoft.com/devcontainers/go:1.22
    command: sleep infinity
    ports:
      - "3000:3000"
    volumes:
      - ../:/workspaces/login-api-optimisation-go
    depends_on:
      - userdb
    environment:
      DB_HOST: userdb
      DB_PORT: "5432"
      DB_NAME: userdb
      DB_USER: user
      DB_PASSWORD: password
      PORT: "3000"
  userdb:
    image: postgres:17.9
    environment:
      POSTGRES_DB: userdb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
