description = "Implement the Saga pattern to coordinate a distributed transaction across PostgreSQL and MySQL services using Kafka for messaging."

[[service]]
name = "booking-service"
runtime = "nodejs"
port = 3000
healthCheckUrl = "/healthcheck"
cpuCores = 0.5
memoryMB = 512
instances = 1
directory = "booking-service"
env = { DATABASE_URL = "postgresql://user:password@pg-booking-service:5432/bookingdb", KAFKA_BROKERS = "kafka:9092", PORT = "3000", AIRLINE1_URL = "http://airline-1-service:4000", AIRLINE2_URL = "http://airline-2-service:5000" }

[[service]]
name = "airline-1-service"
runtime = "nodejs"
port = 4000
healthCheckUrl = "/healthcheck"
cpuCores = 0.5
memoryMB = 512
instances = 1
directory = "airline-1-service"
env = { DATABASE_URL = "postgresql://user:password@pg-airline1:5432/airline1db", PORT = "4000" }

[[service]]
name = "airline-2-service"
runtime = "nodejs"
port = 5000
healthCheckUrl = "/healthcheck"
cpuCores = 0.5
memoryMB = 512
instances = 1
directory = "airline-2-service"
env = { MYSQL_HOST = "mysql-airline2", MYSQL_PORT = "3306", MYSQL_USER = "user", MYSQL_PASSWORD = "password", MYSQL_DATABASE = "airline2db", PORT = "5000" }

[[postgres]]
name = "pg-booking-service"
cpuCores = 0.5
memoryMB = 512
storageGB = 5
dbName = "bookingdb"
user = "user"
password = "password"

[[postgres]]
name = "pg-airline1"
cpuCores = 0.5
memoryMB = 512
storageGB = 5
dbName = "airline1db"
user = "user"
password = "password"

[[mysql]]
name = "mysql-airline2"
cpuCores = 0.5
memoryMB = 512
storageGB = 5
dbName = "airline2db"
user = "user"
password = "password"

[[kafka]]
name = "kafka"
cpuCores = 0.5
memoryMB = 512
storageGB = 5
brokers = 1
topics = [{ name = "saga-commands", partition = 3, replicationFactor = 1 }, { name = "saga-replies", partition = 3, replicationFactor = 1 }]

[[dataseeder]]
file = "booking-service/schema.sql"
targetName = "pg-booking-service"

[[dataseeder]]
file = "airline-1-service/schema.sql"
targetName = "pg-airline1"

[[dataseeder]]
file = "airline-2-service/schema.sql"
targetName = "mysql-airline2"

[apitest]
file = ".nurburgdev/apitest.tavern.yaml"
env = { HOST_BOOKING_SERVICE = "http://booking-service:3000", HOST_AIRLINES_1 = "http://airline-1-service:4000", HOST_AIRLINES_2 = "http://airline-2-service:5000" }

[[score]]
name = "FUNC_TEST"
taskName = "apitest-0"
threshold = 100.0
