services:
    dev:
        image: mcr.microsoft.com/devcontainers/typescript-node:22
        command: sleep infinity
        ports:
            - 3000:3000
        volumes:
            - ../:/workspaces/proud-island
        depends_on:
            - ticketsdb
    ticketsdb:
        image: postgres:17.9
        environment:
            POSTGRES_DB: ticketsdb
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user
