spring.datasource.url=jdbc:postgresql://${DB_HOST:userdb}:${DB_PORT:5432}/${DB_NAME:userdb}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}
server.port=${PORT:8080}
