test_name: Valid login for yvette52

stages:
  - name: Valid login for yvette52
    request:
      url: "{tavern.env_vars.HOST}/auth/login"
      method: POST
      json:
        email: "yvette52@example.org"
        password: "password123"
    response:
      status_code: 200
      json:
        token: !anystr
        user:
          id: !anyint
          email: !anystr
          name: !anystr

---

test_name: Valid login for james37

stages:
  - name: Valid login for james37
    request:
      url: "{tavern.env_vars.HOST}/auth/login"
      method: POST
      json:
        email: "james37@example.org"
        password: "password123"
    response:
      status_code: 200
      json:
        token: !anystr
        user:
          id: !anyint
          email: !anystr
          name: !anystr

---

test_name: Wrong password returns 401

stages:
  - name: Wrong password returns 401
    request:
      url: "{tavern.env_vars.HOST}/auth/login"
      method: POST
      json:
        email: "yvette52@example.org"
        password: "wrongpassword"
    response:
      status_code: 401
